### PR TITLE
Added issue and pull request template

### PR DESCRIPTION
**Pull request by iamrajiv**

### CODE REVIEW

**Comment by iamrajiv** [comment]
@parasg1999 this is failing because I think it is something to do with the SECRET_KEY or you have not enabled GitHub actions in the repository can you check once. I have tested this in my repository and is working fine check this [https://github.com/iamrajiv/test/pull/2](https://github.com/iamrajiv/test/pull/2)

**Comment by iamrajiv** [comment]
@parasg1999 this is failing because I think it is something to do with the SECRET_KEY or you have not enabled GitHub actions in the repository can you check once. I have tested this in my repository and is working fine check this [https://github.com/iamrajiv/test/pull/2](https://github.com/iamrajiv/test/pull/2)

**Comment by parasg1999** [comment]
I don't have rights to the repository, the organizers would have to fix if that's the issue

**Comment by iamrajiv** [comment]
@parasg1999 I think this is ready to be merged.

**Pull request merged**
