### PR TITLE
Added ESLint and Prettier action

### LINKED ISSUE #2: Adding GitHub actions to iBlog

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #2

### CODE REVIEW

**Comment by iamrajiv** [comment]
@parasg1999 Please review

**Comment by parasg1999** [comment]
So, this will format the code on every PR and commit?

**Comment by iamrajiv** [comment]
@parasg1999 Yes

**Comment by parasg1999** [comment]
Wouldn't it be better to just run these on the client side before they push, and just check the PR for errors?
I mean by node scripts

**Comment by iamrajiv** [comment]
@iamrajiv Like in these actions it will check the code format whenever there is a push and pull request to the master branch of iBlog. I am not familiar with how to run it in client-side. I think this will work fine.

**Comment by iamrajiv** [comment]
@parasg1999 In these actions it will check the code format whenever there is a push and pull request to the master branch of iBlog. I am not familiar with how to run it in client-side. I think this will work fine.

**Comment by parasg1999** [comment]
LGTM :tada:

**Pull request merged**
